### ISSUE TITLE
[select courses] scrolling not possible -> not be able to see all courses

### ISSUE THREAD

**Issue by T1m1** [htwg-cloud-application-development/frontend#38] opened 2016-06-22 09:26 UTC
![image](https://cloud.githubusercontent.com/assets/5616884/16261457/f5e13b8e-386b-11e6-8870-be9903e49f61.png)

**Comment by phaldan** [comment] 2016-06-22 20:10
Strange! I cannot reproduce this problem on my local system.

**Comment by T1m1** [comment] 2016-06-22 20:58
Strange, too! Now it works :D

**Comment by phaldan** [comment] 2016-06-23 11:40
Now I could reproduce this problem. It is a side effect of an error in the modal closing.
This error causes, that css-class "modal-open" is not removed from body html-tag.

**Closed as completed** 2016-06-23 13:40 UTC
Labels: bug
